async function main() {}

main()
    .then(() => process.exit(0))
    .catch((e) => {
        console.error(error)
        process.exit(1)
    })
